# Cloud Build for Configure Compute
# Builds editor-ui container and deploys to Cloud Run
# Note: Run from project root directory

steps:
  # Build editor-ui image (includes cc-core WASM build)
  - name: gcr.io/cloud-builders/docker
    id: build-ui
    args:
      - build
      - -f
      - deployment/Dockerfile
      - --build-arg
      - GITHUB_TOKEN=${_GITHUB_TOKEN}
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/configure-compute/configure-compute-editor:$SHORT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/configure-compute/configure-compute-editor:latest
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    id: push-ui
    waitFor: ['build-ui']
    args:
      - push
      - --all-tags
      - us-central1-docker.pkg.dev/$PROJECT_ID/configure-compute/configure-compute-editor

  # Deploy to Cloud Run with config profile injection
  - name: python:3.12-slim
    id: generate-config
    waitFor: ['push-ui']
    entrypoint: bash
    args:
      - -c
      - |
        pip install --no-cache-dir pyyaml
        echo "Generating Cloud Run service spec from config profile: $_CONFIG_PROFILE"
        python deployment/build-config.py \
          deployment/run-service.template.yaml \
          $_CONFIG_PROFILE \
          $SHORT_SHA \
          $PROJECT_ID
    env:
      - PROJECT_ID=$PROJECT_ID
      - SHORT_SHA=$SHORT_SHA

  - name: gcr.io/cloud-builders/gcloud
    id: deploy-service
    waitFor: ['generate-config']
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deploying service..."
        gcloud run services replace deployment/run-service-generated.yaml \
          --region=$_REGION \
          --platform=managed

# Push images to Artifact Registry
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/configure-compute/configure-compute-editor:$SHORT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/configure-compute/configure-compute-editor:latest

# Substitutions with defaults
substitutions:
  _REGION: us-central1
  _CONFIG_PROFILE: production
  _GITHUB_TOKEN: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
