apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
    deploy.cloud.run/commit: "{{SHORT_SHA}}"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "{{MIN_INSTANCES}}"
        autoscaling.knative.dev/maxScale: "{{MAX_INSTANCES}}"
    spec:
      timeoutSeconds: 300
      containerConcurrency: {{CONCURRENCY}}
      serviceAccountName: {{SERVICE_ACCOUNT}}
      containers:
        - name: editor
          image: {{IMAGE}}
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "{{CPU}}"
              memory: {{MEMORY}}
            requests:
              cpu: "{{CPU_REQUEST}}"
              memory: {{MEMORY_REQUEST}}
          env:
            - name: ENVIRONMENT
              value: {{ENVIRONMENT}}
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
